// Substack Post Scraper Script
// This will be run in the browser console to extract content from each post

const posts = [
  {"url":"https://www.the-ai-corner.com/p/openai-pitch-deck-analysis","slug":"openai-pitch-deck-analysis","title":"OpenAI's early pitch deck, broken down","subtitle":"How one of the most important companies in tech learned to explain itself"},
  {"url":"https://www.the-ai-corner.com/p/stop-using-powerpoint-for-serious","slug":"stop-using-powerpoint-for-serious","title":"Stop using PowerPoint for serious decks","subtitle":"Lovable turns your deck into a web app. And it looks unfair."},
  {"url":"https://www.the-ai-corner.com/p/recursive-language-models-rlm-mit","slug":"recursive-language-models-rlm-mit","title":"R.I.P. Basic Prompting","subtitle":"MIT just dropped a technique that changes how AI actually reasons"},
  {"url":"https://www.the-ai-corner.com/p/ai-startup-pitch-decks-library","slug":"ai-startup-pitch-decks-library","title":"The Most Recent AI Startup Decks You Should Study Right Now","subtitle":"A curated library of Pre-Seed and Seed AI companies backed by serious investors"},
  {"url":"https://www.the-ai-corner.com/p/claude-co-work-system","slug":"claude-co-work-system","title":"How Serious Builders Co-Work With Claude","subtitle":"A practical, high-ROI playbook for founders, operators, and creatives"},
  {"url":"https://www.the-ai-corner.com/p/20k-growth-consultant-chatgpt-prompt","slug":"20k-growth-consultant-chatgpt-prompt","title":"Will the Consumer AI Vertical Dominate the Next Decade?","subtitle":"Consumer AI might be the biggest technological wave of this decade, as everyday usage is soaring"},
  {"url":"https://www.the-ai-corner.com/p/sam-altman-openai-interview-ai-deployment-memory-enterprise","slug":"sam-altman-openai-interview-ai-deployment-memory-enterprise","title":"Sam Altman on Where AI Is Actually Going","subtitle":"What OpenAI's CEO revealed about memory, enterprise adoption, and the real opportunity most companies are missing."},
  {"url":"https://www.the-ai-corner.com/p/free-founder-templates-kit-notion","slug":"free-founder-templates-kit-notion","title":"The Free Founder Templates Kit","subtitle":"a full-stack operating system for building, launching, fundraising, and scaling in the AI era"},
  {"url":"https://www.the-ai-corner.com/p/a16z-ai-ideas-2026-partners","slug":"a16z-ai-ideas-2026-partners","title":"a16z Partners Just Laid Out the AI Playbook for 2026","subtitle":"the 15 biggest ideas shaping how software, work, and entire industries will change in 2026"},
  {"url":"https://www.the-ai-corner.com/p/atrios-a16z-speedrun-ai-warm-intros-gtm-2025","slug":"atrios-a16z-speedrun-ai-warm-intros-gtm-2025","title":"From 0 to $1M: How Atrios Used a16z Speedrun to Redefine AI-Era Go-To-Market","subtitle":"Inside Taylor Offer's 12-week sprint through a16z Speedrun, where he built a killer team, closed millions, and created one of the fastest-growing B2B AI…"},
  {"url":"https://www.the-ai-corner.com/p/ilya-sutskever-safe-superintelligence-agi-2025","slug":"ilya-sutskever-safe-superintelligence-agi-2025","title":"Ilya Sutskever's New Playbook for AGI","subtitle":"What his rare interview with Dwarkesh Patel reveals about the future of AI, the end of scaling, Safe Superintelligence Inc., and why humans still win at…"},
  {"url":"https://www.the-ai-corner.com/p/hyperliquid-ai-efficiency-onchain-exchange-2025","slug":"hyperliquid-ai-efficiency-onchain-exchange-2025","title":"Hyperliquid: The 11-Person Exchange That Shows How Extreme AI-Era Efficiency Can Get","subtitle":"What a tiny crypto derivatives team can teach us about the future of AI, agents, and software leverage"},
  {"url":"https://www.the-ai-corner.com/p/ai-agents-roadmap-2025-best-projects-rag-mcp-memory","slug":"ai-agents-roadmap-2025-best-projects-rag-mcp-memory","title":"The Ultimate AI Agent Project Roadmap for 2025","subtitle":"The most complete, curated list of AI agent projects, RAG workflows, memory apps, and MCP tools available today"},
  {"url":"https://www.the-ai-corner.com/p/the-ultimate-ai-agents-roadmap-2025","slug":"the-ultimate-ai-agents-roadmap-2025","title":"The Ultimate AI Agents Roadmap for 2025","subtitle":"A complete, curated guide to videos, repos, papers, and tools for building real agent systems."},
  {"url":"https://www.the-ai-corner.com/p/yc-requests-for-startups-fall-2025-ai-trends","slug":"yc-requests-for-startups-fall-2025-ai-trends","title":"What YC's New Startup Wishlist Says About the Future of AI","subtitle":"YC's latest Requests for Startups outline six frontiers where AI is creating billion-dollar openings — and why timing has never been better to start."},
  {"url":"https://www.the-ai-corner.com/p/the-great-ai-reset","slug":"the-great-ai-reset","title":"The Great AI Reset","subtitle":"What the data shows about who is building, where capital is moving, and how the cycle is shifting"}
];

// Export for use
module.exports = { posts };
